<?xml version="1.0" encoding="UTF-8"?>
	<xsl:stylesheet version="2.0"
		xmlns:html="http://www.w3.org/TR/REC-html40"
		xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
		xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
		xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
		<head>
			<title>XML Sitemap</title>
			<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
			<style type="text/css">
				:root {
					--primary: #0f172a;
					--secondary: #64748b;
					--accent: #0d9488;
					--page-bg: #f8fafc;
					--border: #e2e8f0;
					--content: #334155;
					--entry: #ffffff;
				}
				@media (prefers-color-scheme: dark) {
					:root {
						--primary: #f1f5f9;
						--secondary: #94a3b8;
						--accent: #14b8a6;
						--page-bg: #020617;
						--border: #334155;
						--content: #cbd5e1;
						--entry: #1e293b;
					}
				}
				body {
					font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
					font-size: 14px;
					color: var(--content);
					background-color: var(--page-bg);
					margin: 0;
					padding: 20px;
				}
				#content {
					margin: 0 auto;
					max-width: 1000px;
				}
				h1 {
					color: var(--primary);
					font-size: 24px;
					margin-bottom: 20px;
				}
				.expl {
					margin: 20px 0;
					line-height: 1.6;
					color: var(--secondary);
				}
				.expl a {
					color: var(--accent);
					font-weight: 600;
					text-decoration: none;
				}
				.expl a:hover {
					text-decoration: underline;
				}
				a {
					color: var(--accent);
					text-decoration: none;
				}
				a:hover {
					text-decoration: underline;
				}
				table {
					width: 100%;
					border-collapse: collapse;
					margin-top: 20px;
					background: var(--entry);
					border-radius: 8px;
					overflow: hidden;
					box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
				}
				thead th {
					text-align: left;
					padding: 12px 15px;
					background: var(--primary);
					color: var(--entry);
					font-size: 12px;
					text-transform: uppercase;
					letter-spacing: 0.05em;
				}
				td {
					padding: 12px 15px;
					border-bottom: 1px solid var(--border);
					font-size: 13px;
				}
				td:last-child, th:last-child {
					white-space: nowrap;
					text-align: right;
				}
				#sitemap tbody tr:last-child td {
					border-bottom: none;
				}
				#sitemap tbody tr:hover td {
					background-color: var(--page-bg);
				}
			</style>
		</head>
		<body>
		<div id="content">
			<h1>XML Sitemap</h1>
			<p class="expl">
				Generated by <a href="https://omid.dev" target="_blank" rel="noopener">omid.dev</a>, this is an XML Sitemap, meant for consumption by search engines.<br/>
				You can find more information about XML sitemaps on <a href="https://sitemaps.org" target="_blank" rel="noopener">sitemaps.org</a>.
			</p>
			<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
				<p class="expl">
					This XML Sitemap Index file contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps.
				</p>
				<table id="sitemap">
					<thead>
					<tr>
						<th>Sitemap</th>
						<th>Last Modified</th>
					</tr>
					</thead>
					<tbody>
					<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
						<xsl:variable name="sitemapURL">
							<xsl:value-of select="sitemap:loc"/>
						</xsl:variable>
						<tr>
							<td>
								<a href="{$sitemapURL}"><xsl:value-of select="sitemap:loc"/></a>
							</td>
							<td>
								<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))"/>
							</td>
						</tr>
					</xsl:for-each>
					</tbody>
				</table>
			</xsl:if>
			<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &lt; 1">
				<p class="expl">
					This XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.
				</p>
				<table id="sitemap">
					<thead>
					<tr>
						<th>URL</th>
						<th>Images</th>
						<th title="Last Modification Time">Last Mod.</th>
					</tr>
					</thead>
					<tbody>
					<xsl:variable name="lower" select="'abcdefghijklmnopqrstuvwxyz'"/>
					<xsl:variable name="upper" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'"/>
					<xsl:for-each select="sitemap:urlset/sitemap:url">
						<tr>
							<td>
								<xsl:variable name="itemURL">
									<xsl:value-of select="sitemap:loc"/>
								</xsl:variable>
								<a href="{$itemURL}">
									<xsl:value-of select="sitemap:loc"/>
								</a>
							</td>
							<td>
								<xsl:value-of select="count(image:image)"/>
							</td>
							<td>
								<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))"/>
							</td>
						</tr>
					</xsl:for-each>
					</tbody>
				</table>
			</xsl:if>
		</div>
		</body>
		</html>
	</xsl:template>
	</xsl:stylesheet>
